### ISSUE TITLE
这工具是不是被b站封了

### ISSUE THREAD

**Issue by ghost** [tohno-kun/bilibili-playlist#5]
现在通过工具观看视频会提提示如下内容，直接访问h5播放器地址也是返回这个提示
![](https://github.com/whobuki/img/raw/master/QQ%E5%9B%BE%E7%89%8720171118205041.png)

**Comment by tohno-kun** [comment]
@whobuki 
这个问题刚才已修复，原因是因为b站的h5视频服务器修改了url，晚上VPN挂掉了，明天连上之后，会同步更新到chrome应用商店。

**Comment by tohno-kun** [comment]
@whobuki 链接失效bug已修复。vpn更新即可。或导出当前列表重新安装。
PS：pick up girls！列表已重新制作，原链接失效。
